#
# Module manifest for module 'DefenderDeviceControlUnmanaged'
#
# Generated by: Luke Evans
#
# Generated on: 16/04/2025
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'DefenderDeviceControlUnmanaged.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core','Desktop')

    # ID used to uniquely identify this module
    GUID              = 'defdd5b2-8053-4250-b150-6ec31bf0f892'

    # Author of this module
    Author            = 'Luke Evans'

    # Company or vendor of this module
    CompanyName       = 'LukeEvansTech'

    # Copyright statement for this module
    Copyright         = 'Copyright (c) 2026 Luke Evans'

    # Description of the functionality provided by this module
    Description       = 'Microsoft Defender Device Control for unmanaged Windows 11 devices - no Intune, no domain GPO, no MDM. Apply, audit, and verify the canonical Local GPO Device Control registry surface from a single PowerShell cmdlet.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'Get-DefenderDcPolicy',
        'Invoke-DefenderDcOnboarding',
        'Invoke-DefenderDcUsbTest',
        'Set-DefenderDcPolicy',
        'Test-DefenderDcPolicy',
        'Test-DefenderDcPolicyXml'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{
            Tags = @('Defender','DeviceControl','USB','MDE','Security','Windows','Unmanaged','GroupPolicy')
            LicenseUri = 'https://github.com/LukeEvansTech/defender-device-control-unmanaged/blob/main/LICENSE'
            ProjectUri = 'https://github.com/LukeEvansTech/defender-device-control-unmanaged'
            # IconUri set after release; PSGallery rejects empty strings.
            ReleaseNotes = 'See https://github.com/LukeEvansTech/defender-device-control-unmanaged/blob/main/CHANGELOG.md'
        }
    }

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
