name: Security Scans

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    uses: LukeEvansTech/shared-workflows/.github/workflows/security-scans.yml@4a27af481a70705a65b82c72ef62fc58c5af6ed0 # v1
    with:
      checkov-frameworks: github_actions
      trivy-scanners: vuln,secret,misconfig
