name: Security Scans

on:
  pull_request:
  push:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
    uses: LukeEvansTech/shared-workflows/.github/workflows/security-scans.yml@3771e1f9da1b3f6132eec9d63aacc0acb74660bc # v1
    with:
      checkov-frameworks: github_actions
      trivy-scanners: vuln,secret,misconfig
